version: '3'

services:
  app:
    image: node:16
    tty: true
    volumes:
      - ./:/var/www/app
      # - node_packages:/var/www/app/node_modules
    working_dir: /var/www/app
    ports:
      - "3000:3000"
      - "4000:4000"
    environment:
      - CHOKIDAR_USEPOLLING=true

# volumes:
#   node_packages:
